name: Test AWS Secrets

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Test AWS connection
      run: |
        echo "Testing AWS connection..."
        aws sts get-caller-identity
        echo "✅ AWS credentials are working!"
        
    - name: List S3 buckets
      run: |
        echo "Available S3 buckets:"
        aws s3 ls
